Blog app - integration specs for views and fix n+1 problems
SAZZAD1Q2/Blog-Web pull request #4
Opened 2023-10-04 11:29 UTC by SAZZAD1Q2

Use Capybara to write integration tests for each view in your project.

Think on the flow of things and group the tests of page in a way that makes sense. For example, one test would check for the things in the page and another test for clicking links on it.

User index page:

    I can see the username of all other users.
    I can see the profile picture for each user.
    I can see the number of posts each user has written.
    When I click on a user, I am redirected to that user's show page.

user show page:

    I can see the user's profile picture.
    I can see the user's username.
    I can see the number of posts the user has written.
    I can see the user's bio.
    I can see the user's first 3 posts.
    I can see a button that lets me view all of a user's posts.
    When I click a user's post, it redirects me to that post's show page.
    When I click to see all posts, it redirects me to the user's post's index page.

2023-10-04 12:16 UTC, thecodechaser requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @SAZZAD1Q2, and @Theodoraldo👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
- Good job fixing n+1 problems. ✔️
- No linter errors. :heavy_check_mark:
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-04 12:16 UTC, thecodechaser commented on spec/feature/capybara_spec.rb
> +    end
- [ ] Currently, you have added tests for all pages in a single file. Please make sure to separate them into different files. It will make the code more readable and clean.
 - Suggested file structure example  for `users#index` page. `feature/users/index_spec.rb`.

2023-10-04 12:16 UTC, thecodechaser commented on spec/feature/capybara_spec.rb
> +
- [ ] You missed adding the below tests for the `users#show` page. Please make sure to add them and they should pass without any errors.
  - Tests that assert you can see the user's first 3 posts.
  - Tests that redirect to the post's show page when you click on a user's post.

2023-10-04 12:16 UTC, thecodechaser commented on spec/feature/capybara_spec.rb
> +
- [ ] You missed adding the below tests for the `posts#index` page. Please make sure to add them and they should pass without any errors.
  - Tests that assert you can see the first comments on a post.

2023-10-04 12:16 UTC, thecodechaser commented on spec/feature/capybara_spec.rb
> +    before do
- [ ] You missed adding the below tests for the `posts#index` page. Please make sure to add them and they should pass without any errors.
  - Tests that assert you can see the username of each comment.
  - Tests that assert you can see the comment each comment left.

2023-10-04 15:18 UTC, Gambit142 requested changes
Hi @SAZZAD1Q2 @Theodoraldo 👋, 

Great work on making the changes requested by a previous reviewer 👏 

## Highlights
- Setup linters properly ✔️ 
- Used `Rspec` as testing library ✔️ 
- Wrote feature tests for Users and Posts pages ✔️ 

You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

N/A

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-04 15:18 UTC, Gambit142 commented on spec/feature/post_index_spec.rb
> +end
- [ ] Great work making all the changes requested by the previous reviewer. However, I noticed that all the tests didn't pass. Kindly fix the issues and ensure that all the tests pass. 👍 

![image](https://github.com/SAZZAD1Q2/Blog-Web/assets/77106962/a6529194-294e-4298-913a-39bac1f8aad0)

2023-10-05 16:13 UTC, uwadonat approved these changes
## Hi @SAZZAD1Q2,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### Congratulations! 🎉 
### Highlights
- Your tests pass successfully ✔️
- No linter errors ✔️
- Correct workflow was used ✔️

# Status: Approved ✔️✔️✔️

![approv](https://github.com/SAZZAD1Q2/Blog-Web/assets/65860678/bcd719b8-e46f-4ad3-9632-15ad69c91905)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100%.
Please, remember to tag me @uwadonat in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-10-05 16:15 UTC, merged